### PR TITLE
Added Software_Architecture.md for user story Maintainer - Architecture Documentation #120

### PR DESCRIPTION
**Pull request by NoorMohamed1885**

### CODE REVIEW

**Comment by Garret-Gallant** [comment]
Nice work Noor!

**Comment by JamiBean** [comment]
good job Noor! Thank you, group

**Comment by jody** [comment]
Which issue is this PR intended to address? From the files themselves it is unclear that this matches the acceptance criteria of a particular user story.

**Comment by NoorMohamed1885** [comment]
Hello professor I forgot to mention it in the title which I will update but this is for ready user story maintainer architecture documentation #120.

**Review by jody — CHANGES_REQUESTED** [review]
How does pull_request_template.md fit with the acceptance criteria of #120 ?
Likewise for build_instructions.md ?
The file Software_Architecture.md doesn't appear to address the "architecture" (design) of the software. How is this related to #120 ?

**Review by jody — CHANGES_REQUESTED** [review]
Why are there 9 changed files in this PR?

Please close and open a new PR with only the necessary updates.

**Review by jody — CHANGES_REQUESTED** [review]
This appears to be a moot PR.  Please close.

**Pull request closed without merging**
