### PR TITLE
Added a class for inputting criteria

### PR DESCRIPTION
**Pull request by Brautigancody465**
Take user input for criteria

### CODE REVIEW

**Comment by Brautigancody465** [comment]
Cody Brautigan pull request 11/6

**Comment by trklenk01** [comment]
Thomas Klenk, pull request in response to issue #115

**Review by jody — CHANGES_REQUESTED** [review]
1. This appears to be an implementation without associated tests.
Please see: [Test-Driven Development](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/DevelopmentConventions.md#test-driven-development)
2. Missing demonstration of code quality (compilation, unit test results, code convention adherence).
3. The project already provides a class with a main method: [DSSDriver.java](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/src/metrocs/DSDriver.java). No clear description of how this class is intended to fit into the existing project.

**Comment by jody** [comment]
Considered to be a practice PR.

**Pull request closed without merging**
