### PR TITLE
119-Added use of PMD source code analyzer

### LINKED ISSUE #119: [USER-STORY] Maintainer use of PMD source code analyzer
# User Story
Recognized stakeholder types: Decision-Maker, Maintainer

## Story
As a _Maintainer_  <br>
I want _PMD enabled in the build_ <br>
so that _the source code can be analyzed by PMD for common weaknesses_.

### Rules
* The automated build process (via Ant) supports PMD
* "pmd" exists as an Ant target
* PMD is included in the Ant "all" target

## Supporting Information
_[Relevant information, context, resources, references]_
* https://docs.pmd-code.org/pmd-doc-7.7.0/pmd_userdocs_installation.html
* https://docs.pmd-code.org/pmd-doc-7.7.0/pmd_userdocs_tools_ant.html
* `wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.7.0/pmd-dist-7.7.0-bin.zip`

Projects with examples of use:
* [imagelab](https://github.com/MetroCS/imagelab)
* [redistricting](https://github.com/MetroCS/redistricting)

### Depends On   
_[__Links__ to other issues on which this story depends]_  
### Dependents  
_[__Links__ to other issues that depend on this story]_

### PR DESCRIPTION
**Pull request by jmaestas7**
Resolves #119

### CODE REVIEW

**Review by jody — COMMENTED** [review]
Is there a reason for us not to use the current release of PMD (7.7.0)?
https://docs.pmd-code.org/pmd-doc-7.7.0/pmd_release_notes.html

**Comment by jmaestas7** [comment]
We aren't using the latest version because it was simpler to just use the existing .jars's in the imagalab project and we found it to be an unnecessary time waste to try and filter out the required jars for PMD@7.7.0.

We also discussed this in class with you, and it was agreed that using this approach and using the latest version is a want, not a need, and will be implemented in a different user story.

**Comment by jody** [comment]
> We aren't using the latest version because it was simpler to just use the existing .jars's in the imagalab project and we found it to be an unnecessary time waste to try and filter out the required jars for PMD@7.7.0.

Makes good sense! Thanks!

**Review by jody — APPROVED** [review]

**Comment by jody** [comment]
Closes #119

**Pull request merged**
