### PR TITLE
setup method declerations for testing implementation

### PR DESCRIPTION
**Pull request by Korgath1**

### CODE REVIEW

**Comment by jody** [comment]
Why is there no description provided for this PR? What is its intent? Which issue is i9t addressing? Who else worked on this?

**Review by jody — CHANGES_REQUESTED** [review]
The comments in the code do not appear to match the code itself.

Why is there a "main" method in this new class? Is this intended to replace DSSDriver?

Please demonstrate that this compiles without errors and that it matches the coding standards for the project.

**Review by jody — CHANGES_REQUESTED** [review]
Extraneous file in this PR: helloCS3250/build/jar/HelloWorld.jar

Please close this PR and open a new one with only the commits associated with the issue (which is also not yet identified).

**Comment by Angela-Fl** [comment]
I am a contributor in this group.  Will address requested changes in class.

**Comment by jody** [comment]
Closing under the assumption that this was a practice PR.

**Pull request closed without merging**
