### PR TITLE
Created Documentation Directory

### PR DESCRIPTION
**Pull request by jerem-dough**
Added Documentation directory, and moved current documentation inside.

### CODE REVIEW

**Comment by jody** [comment]
Which issue (user-story) is this PR addressing?
What are the acceptance criteria that this PR fulfills?
Who has worked on this with you?

**Comment by jerem-dough** [comment]
This isn't my submission, but it seems like a relevant addition to the repo.

**Review by jody — CHANGES_REQUESTED** [review]
Every "good idea" needs to be reviewed, clarified as needed, and prioritized if accepted. These are done through issue tracking. Likewise, PRs match with identified and accepted concerns and desires of the project. (PRs not associated with specific, articulated project goals are perceived as "arbitrary".)

**Comment by jody** [comment]
Not sure what you meant by this not being your submission.
If you didn't intend to make this PR, you can close it.

**Pull request closed without merging**
