### PR TITLE
[USER-STORY] Decision-Maker defines decision criteria #115

### PR DESCRIPTION
**Pull request by Nitnop**
by cove and tristan

### CODE REVIEW

**Review by jody — CHANGES_REQUESTED** [review]
This PR does not appear to be relevant to issue #115 

It doesn't appear to be relevant to any of the currently open issues.

**Comment by jody** [comment]
The only participant shown in GitHub is Nitnop. (GitHub does not parse comments for meaning.)

There's no description associated with this PR. The intial comment doesn't reference the intent or directly link to an issue.

The changes proposed in this PR do not appear to be relevant to the acceptance criteria for the issue given in the title.

Please review the issue and its acceptance criteria in the context of the project documentation and the live demonstration of the behavior of the decision support aid.

Rather than trying to rework the title, description, and content of this PR, it is likely better to start fresh.

**Comment by Nitnop** [comment]
fine, after the user finishes entering things to choose from it starts printing them out and making the user choose.

**Review by jody — CHANGES_REQUESTED** [review]
The addition of a file named "This is where documentation goes.txt" doesn't have an obvious connection to the user story #115 

Can you please review of [System Components](https://github.com/MetroCS/cs3250_practice/blob/main/decision_support/DSSProcess.md#2-system-components) to see if there's a better way to describe the intent of #115 ?

**Review by jody — CHANGES_REQUESTED** [review]
This appears to be off-task as a PR for User Story #115

**Comment by jody** [comment]
Please close.  (You may wish to review PR #138 as an attempt to address User Story #115 )

**Comment by Nitnop** [comment]
fuck everyting

**Pull request closed without merging**
